on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.x"
jobs:
  deps:
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dev Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Build
        shell: bash
        run: |
          python ./bin/build.py --zip
      - name: Find zip file
        id: find
        shell: bash
        run: |
          echo "::set-output name=prop::$(find . -name '*.zip')"
      - name: Get version
        id: version
        run: |
          echo "::set-output name=prop::$(python ./bin/build.py --version)"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "${{ steps.find.outputs.prop }}"
          tag_name: "v${{ steps.version.outputs.prop }}"
          generate_release_notes: true
          prerelease: "${{ contains(steps.version.outputs.prop, 'dev') || contains(steps.version.outputs.prop, 'rc') }}"
permissions:
  contents: write
