name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - "v*"
    paths-ignore:
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: 3.8
jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      python-version: 3.8
    permissions:
      contents: write
