name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - rc
    tags-ignore:
      - "*"
    paths-ignore:
      - .github/workflows/*
      - README.md
      - assets/*
      - bin/*
env:
  PYTHON_VER: 3.8
jobs:
  publish:
    uses: ./.github/workflows/build-pub.yml
    with:
      python-version: 3.8
    permissions:
      contents: write
