name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - "v*"
    paths-ignore:
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: 3.8
jobs:
  deps:
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dev Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Build
        shell: bash
        run: |
          python ./bin/build.py --zip
      - name: Find zip file
        id: find
        run: |
          echo "prop=$(ls -t **/*.zip | head -1)" >> $GITHUB_ENV
      - name: Get version
        id: version
        run: |
          echo "prop=$(python ./bin/build.py --version)" >> $GITHUB_ENV
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "${{ steps.find.outputs.prop }}"
          tag_name: "${{ steps.version.outputs.prop }}"
          generate_release_notes: true
          prerelease: "${{ contains(steps.version.outputs.prop, 'dev') || contains(steps.version.outputs.prop, 'rc') }}"
permissions:
  contents: write
